import type { HourCode } from 'gnss-js/time';

export type TimeResult = {
  weekNumber: number;
  timeOfWeek: number;
  gpsTime: number;
  galTime: number;
  bdsTime: number;
  unixTime: number;
  dayOfYear: number;
  weekOfYear: number;
  timeOfDay: number;
  dayOfWeek: number;
  hourCode: HourCode;
  julianDate: string;
  mjd: string;
  mjd2000: string;
  leapTaiUtc: number;
  leapGpsUtc: number;
  gloN4: number;
  gloNa: number;
  dateTai: string;
  timeTai: string;
  dateTT: string;
  timeTT: string;
  dateUtc: string;
  timeUtc: string;
  dateGps: string;
  timeGps: string;
  rinex: string;
};
