/**
 * PDF Report generator using Typst (compiled to WASM in the browser).
 * Produces LaTeX-quality typeset documents with proper typography,
 * booktabs-style tables, numbered sections, and embedded SVG charts.
 *
 * The ~10 MB WASM compiler is lazy-loaded from CDN on first use and cached.
 */

import { $typst } from '@myriaddreamin/typst.ts/dist/esm/contrib/snippet.mjs';
import type { ReportData } from '../util/report-types';
import {
  renderSkyPlotSvg,
  renderMultipathElevSvg,
  renderCn0TimelineSvg,
  renderSatCountSvg,
  renderCn0DistributionSvg,
  renderElevCn0Svg,
  renderCycleSlipRateSvg,
  renderCompletenessBarSvgs,
  renderMultipathRmsBarSvg,
  renderMultipathPerSatSvg,
  getMultipathStatsRows,
  PRINT_THEME,
} from '../util/report-charts';
import { systemName, systemCmp } from 'gnss-js/rinex';

export type { ReportData } from '../util/report-types';

/* ================================================================== */
/*  Typst compiler initialization                                       */
/* ================================================================== */

let initialized = false;

function ensureInit(): void {
  if (initialized) return;
  $typst.setCompilerInitOptions({
    getModule: () =>
      'https://cdn.jsdelivr.net/npm/@myriaddreamin/typst-ts-web-compiler@0.7.0-rc2/pkg/typst_ts_web_compiler_bg.wasm',
  });
  initialized = true;
}

/* ================================================================== */
/*  Helpers                                                              */
/* ================================================================== */

function formatTime(d: Date): string {
  return d.toISOString().replace('T', ' ').replace('Z', ' UTC');
}

function formatDuration(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

function formatEcef(xyz: [number, number, number]): string {
  return `${xyz[0].toFixed(4)}, ${xyz[1].toFixed(4)}, ${xyz[2].toFixed(4)} m`;
}

/** Escape special Typst characters */
function esc(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/#/g, '\\#')
    .replace(/\$/g, '\\$')
    .replace(/</g, '\\<')
    .replace(/>/g, '\\>')
    .replace(/@/g, '\\@')
    .replace(/_/g, '\\_')
    .replace(/\*/g, '\\*');
}

/* ================================================================== */
/*  Typst document builder                                               */
/* ================================================================== */

function buildTypstDocument(
  data: ReportData,
  chartFiles: string[],
  hasLogo: boolean,
): string {
  const {
    header,
    stats,
    warnings,
    grid: _grid,
    qaResult,
    obsFileNames,
    navFileNames,
  } = data;
  const station = esc(header.markerName || obsFileNames[0] || 'RINEX Analysis');
  const now = new Date();

  const lines: string[] = [];
  const ln = (s: string) => lines.push(s);

  // ── Page setup ──────────────────────────────────────────────
  ln(`// Page setup`);
  ln(
    `#set document(title: "${station} — RINEX Analysis Report", author: "gnsscalc.com")`,
  );
  ln(`#set page(`);
  ln(`  paper: "a4",`);
  ln(`  margin: (top: 2.8cm, bottom: 2.2cm, left: 2cm, right: 2cm),`);
  ln(`  header: context {`);
  ln(`    if counter(page).get().first() > 1 [`);
  ln(`      #set text(8pt, fill: rgb("#999999"))`);
  ln(`      ${station} #h(1fr) RINEX Observation Analysis`);
  ln(`      #v(2pt)`);
  ln(`      #line(length: 100%, stroke: 0.4pt + rgb("#cccccc"))`);
  ln(`    ]`);
  ln(`  },`);
  ln(`  footer: context [`);
  ln(`    #line(length: 100%, stroke: 0.4pt + rgb("#cccccc"))`);
  ln(`    #v(2pt)`);
  ln(`    #set text(8pt, fill: rgb("#999999"))`);
  ln(
    `    Generated by gnsscalc.com #h(1fr) #counter(page).display("1 / 1", both: true)`,
  );
  ln(`  ],`);
  ln(`)`);
  ln(``);
  ln(`#set text(font: "New Computer Modern", size: 10pt, lang: "en")`);
  ln(`#set par(justify: true, leading: 0.65em)`);
  ln(`#set heading(numbering: "1.")`);
  ln(`#show figure: set block(breakable: true)`);
  ln(``);

  // ── Custom heading styles ───────────────────────────────────
  ln(`#show heading.where(level: 1): it => {`);
  ln(`  v(1.2em)`);
  ln(`  set text(14pt, weight: "bold")`);
  ln(`  if it.numbering != none {`);
  ln(`    block[#counter(heading).display() #it.body]`);
  ln(`  } else {`);
  ln(`    block[#it.body]`);
  ln(`  }`);
  ln(`  v(0.6em)`);
  ln(`}`);
  ln(``);
  ln(`#show heading.where(level: 2): it => {`);
  ln(`  v(0.8em)`);
  ln(`  set text(12pt, weight: "bold")`);
  ln(`  block[#counter(heading).display() #it.body]`);
  ln(`  v(0.4em)`);
  ln(`}`);
  ln(``);

  // ── Cover page ──────────────────────────────────────────────
  if (hasLogo) {
    ln(`#v(3cm)`);
    ln(`#align(center)[#image("/logo.png", width: 8cm)]`);
    ln(`#v(1.5cm)`);
  } else {
    ln(`#v(6cm)`);
  }
  ln(`#align(center)[`);
  ln(`  #text(26pt, weight: "bold")[${station}]`);
  ln(`  #v(0.4cm)`);
  ln(`  #text(14pt, fill: rgb("#555555"))[RINEX Observation Analysis Report]`);
  ln(`  #v(1cm)`);
  ln(`  #line(length: 4cm, stroke: 2pt + rgb("#2563eb"))`);
  ln(`  #v(1cm)`);
  ln(`  #set text(10pt)`);
  ln(`  #grid(`);
  ln(`    columns: (5em, 1fr),`);
  ln(`    column-gutter: 1em,`);
  ln(`    row-gutter: 0.5em,`);
  ln(`    align: (right, left),`);
  ln(`    [*Date:*], [${now.toISOString().slice(0, 10)}],`);
  if (stats.startTime) {
    const period =
      formatTime(stats.startTime) +
      (stats.endTime ? ` to ${formatTime(stats.endTime)}` : '');
    ln(`    [*Period:*], [${esc(period)}],`);
  }
  const allFiles = [...obsFileNames, ...navFileNames];
  if (allFiles.length <= 4) {
    ln(`    [*Files:*], [${allFiles.map((f) => esc(f)).join(', ')}],`);
  } else {
    // Summarize file counts instead of listing 100+ filenames
    const parts: string[] = [];
    if (obsFileNames.length > 0)
      parts.push(
        `${obsFileNames.length} observation file${obsFileNames.length > 1 ? 's' : ''}`,
      );
    if (navFileNames.length > 0)
      parts.push(
        `${navFileNames.length} navigation file${navFileNames.length > 1 ? 's' : ''}`,
      );
    ln(`    [*Files:*], [${parts.join(', ')} (${allFiles.length} total)],`);
  }
  ln(`    [*Tool:*], [gnsscalc.com],`);
  ln(`  )`);
  ln(`]`);
  ln(`#pagebreak()`);
  ln(``);

  // ── 1. Station Information ──────────────────────────────────
  ln(`= Station Information`);
  ln(``);
  const kvPairs: [string, string][] = [];
  if (header.markerName) kvPairs.push(['Marker name', header.markerName]);
  if (header.markerType) kvPairs.push(['Marker type', header.markerType]);
  if (header.receiverType) {
    const recv =
      header.receiverType +
      (header.receiverVersion ? ` (${header.receiverVersion})` : '');
    kvPairs.push(['Receiver', recv]);
  }
  if (header.antType) {
    const ant =
      header.antType + (header.antNumber ? ` #${header.antNumber}` : '');
    kvPairs.push(['Antenna', ant]);
  }
  if (header.approxPosition)
    kvPairs.push(['ECEF position', formatEcef(header.approxPosition)]);
  if (header.antDelta)
    kvPairs.push([
      'Ant. delta H/E/N',
      header.antDelta.map((v) => v.toFixed(4)).join(', '),
    ]);
  if (header.observer) kvPairs.push(['Observer', header.observer]);
  if (header.agency) kvPairs.push(['Agency', header.agency]);
  kvPairs.push(['RINEX version', header.version.toFixed(2)]);

  ln(`#grid(`);
  ln(`  columns: (10em, 1fr),`);
  ln(`  column-gutter: 1em,`);
  ln(`  row-gutter: 0.4em,`);
  for (const [label, value] of kvPairs) {
    ln(`  text(fill: rgb("#666666"))[${esc(label)}], [${esc(value)}],`);
  }
  ln(`)`);
  ln(``);

  // ── 2. Observation Summary ──────────────────────────────────
  ln(`= Observation Summary`);
  ln(``);

  // Summary table
  const summaryRows: [string, string][] = [];
  if (stats.startTime)
    summaryRows.push(['Start time', formatTime(stats.startTime)]);
  if (stats.endTime) summaryRows.push(['End time', formatTime(stats.endTime)]);
  if (stats.duration != null && stats.duration > 0)
    summaryRows.push(['Duration', formatDuration(stats.duration)]);
  if (stats.interval != null)
    summaryRows.push(['Interval', `${stats.interval} s`]);
  summaryRows.push(['Epochs', String(stats.totalEpochs)]);
  summaryRows.push([
    'Constellations',
    stats.systems.map((s) => systemName(s)).join(', '),
  ]);
  summaryRows.push(['Unique satellites', String(stats.uniqueSatellites)]);
  summaryRows.push(['Mean satellites/epoch', stats.meanSatellites.toFixed(1)]);
  if (stats.meanSnr != null)
    summaryRows.push(['Mean C/N0', `${stats.meanSnr.toFixed(1)} dB-Hz`]);

  ln(`#figure(`);
  ln(`  table(`);
  ln(`    columns: (12em, 1fr),`);
  ln(`    stroke: none,`);
  ln(`    align: (left, left),`);
  ln(`    inset: (x: 8pt, y: 5pt),`);
  ln(`    table.hline(stroke: 1.2pt),`);
  ln(`    table.header([*Parameter*], [*Value*]),`);
  ln(`    table.hline(stroke: 0.5pt),`);
  for (const [param, val] of summaryRows) {
    ln(`    [${esc(param)}], [${esc(val)}],`);
  }
  ln(`    table.hline(stroke: 1.2pt),`);
  ln(`  ),`);
  ln(`  kind: table,`);
  ln(`  caption: [Observation summary],`);
  ln(`) <tab-summary>`);

  ln(``);

  // Observation types table
  const obsTypeEntries = Object.entries(header.obsTypes)
    .filter(([sys]) => sys !== '_v2')
    .sort(([a], [b]) => systemCmp(a, b));

  if (obsTypeEntries.length > 0) {
    ln(`== Observation Types`);
    ln(``);
    ln(`#figure(`);
    ln(`  table(`);
    ln(`    columns: (8em, 1fr),`);
    ln(`    stroke: none,`);
    ln(`    align: (left, left),`);
    ln(`    inset: (x: 8pt, y: 5pt),`);
    ln(`    table.hline(stroke: 1.2pt),`);
    ln(`    table.header([*System*], [*Observation codes*]),`);
    ln(`    table.hline(stroke: 0.5pt),`);
    for (const [sys, codes] of obsTypeEntries) {
      ln(
        `    [${esc(systemName(sys))}], [#set text(size: 8pt); #raw("${codes.join(' ')}")],`,
      );
    }
    ln(`    table.hline(stroke: 1.2pt),`);
    ln(`  ),`);
    ln(`  kind: table,`);
    ln(`  caption: [Observation types per constellation],`);
    ln(`) <tab-obstypes>`);

    ln(``);
  }

  // Validation warnings
  if (warnings.items.length > 0) {
    ln(`== Validation`);
    ln(``);
    for (const w of warnings.items) {
      const icon =
        w.severity === 'error'
          ? '#text(fill: rgb("#dc2626"))[\\u{25CF}]'
          : w.severity === 'warning'
            ? '#text(fill: rgb("#d97706"))[\\u{25CF}]'
            : '#text(fill: rgb("#999999"))[\\u{25CF}]';
      const countStr = w.count > 1 ? ` (${w.count}×)` : '';
      const exStr = w.examples ? ` — ${w.examples.join(', ')}` : '';
      ln(`- ${icon} ${esc(w.message)}${countStr}${esc(exStr)}`);
    }
    ln(``);
  }

  // ── 3. Observation Quality (charts) ─────────────────────────
  ln(`#pagebreak(weak: true)`);
  ln(`= Observation Quality`);
  ln(``);

  // Sky plot — give it its own space
  if (chartFiles.includes('skyplot.svg')) {
    ln(`#figure(`);
    ln(`  image("/skyplot.svg", width: 80%),`);
    ln(`  caption: [Sky plot — satellite tracks over the observation period],`);
    ln(`) <fig-skyplot>`);
    ln(``);
  }

  // Sat count + C/N0 together on next page
  const hasTimelines =
    chartFiles.includes('satcount.svg') || chartFiles.includes('cn0.svg');
  if (hasTimelines) {
    ln(`#pagebreak(weak: true)`);
  }

  if (chartFiles.includes('satcount.svg')) {
    ln(`#figure(`);
    ln(`  image("/satcount.svg", width: 100%),`);
    ln(`  caption: [Number of tracked satellites over time],`);
    ln(`) <fig-satcount>`);
    ln(``);
  }

  if (chartFiles.includes('cn0.svg')) {
    ln(`#figure(`);
    ln(`  image("/cn0.svg", width: 100%),`);
    ln(`  caption: [Mean C/N0 per constellation over time],`);
    ln(`) <fig-cn0>`);
    ln(``);
  }

  // C/N0 distribution
  if (chartFiles.includes('cn0dist.svg')) {
    ln(`#figure(`);
    ln(`  image("/cn0dist.svg", width: 100%),`);
    ln(`  caption: [C/N0 distribution by constellation],`);
    ln(`) <fig-cn0dist>`);
    ln(``);
  }

  // Elevation vs C/N0
  if (chartFiles.includes('elevcn0.svg')) {
    ln(`#figure(`);
    ln(`  image("/elevcn0.svg", width: 100%),`);
    ln(`  caption: [Mean C/N0 vs satellite elevation per frequency band],`);
    ln(`) <fig-elevcn0>`);
    ln(``);
  }

  // ── 4. Multipath Analysis ───────────────────────────────────
  if (qaResult) {
    ln(`#pagebreak(weak: true)`);
    ln(`= Multipath Analysis`);
    ln(``);

    const mpRows = getMultipathStatsRows(qaResult.multipath);
    if (mpRows.length > 0) {
      ln(`#figure(`);
      ln(`  table(`);
      ln(`    columns: (1fr, auto, auto, auto),`);
      ln(`    stroke: none,`);
      ln(`    inset: (x: 8pt, y: 5pt),`);
      ln(`    align: (left, right, right, right),`);
      ln(`    table.hline(stroke: 1.2pt),`);
      ln(
        `    table.header([*Signal*], [*RMS (m)*], [*Observations*], [*Satellites*]),`,
      );
      ln(`    table.hline(stroke: 0.5pt),`);
      for (const row of mpRows.sort((a, b) => systemCmp(a.system, b.system))) {
        const countStr = String(row.count);
        ln(
          `    [${esc(row.label)}], [${row.rms}], [${countStr}], [${row.satellites}],`,
        );
      }
      ln(`    table.hline(stroke: 1.2pt),`);
      ln(`  ),`);
      ln(`  kind: table,`);
      ln(`  caption: [Multipath combination RMS statistics],`);
      ln(`) <tab-multipath>`);

      ln(``);
    }

    if (chartFiles.includes('mp-rmsbar.svg')) {
      ln(`#figure(`);
      ln(`  image("/mp-rmsbar.svg", width: 100%),`);
      ln(`  caption: [Multipath RMS per signal combination],`);
      ln(`) <fig-mp-rmsbar>`);
      ln(``);
    }

    if (chartFiles.includes('multipath.svg')) {
      ln(`#figure(`);
      ln(`  image("/multipath.svg", width: 100%),`);
      ln(`  caption: [Multipath RMS vs satellite elevation],`);
      ln(`) <fig-multipath>`);
      ln(``);
    }

    if (chartFiles.includes('mp-persat.svg')) {
      ln(`#figure(`);
      ln(`  image("/mp-persat.svg", width: 100%),`);
      ln(`  caption: [Per-satellite multipath RMS],`);
      ln(`) <fig-mp-persat>`);
      ln(``);
    }
  }

  // ── 5. Cycle Slip Analysis ──────────────────────────────────
  if (qaResult) {
    const csStats = qaResult.cycleSlips.signalStats;
    const totalSlips = csStats.reduce((sum, s) => sum + s.totalSlips, 0);
    // Only show signals that actually have slips in the table
    const csWithSlips = csStats
      .filter((s) => s.totalSlips > 0)
      .sort((a, b) => systemCmp(a.system, b.system));

    ln(`#pagebreak(weak: true)`);
    ln(`= Cycle Slip Analysis`);
    ln(``);

    if (csWithSlips.length > 0) {
      ln(`#figure(`);
      ln(`  table(`);
      ln(`    columns: (1fr, auto, auto, auto, auto),`);
      ln(`    stroke: none,`);
      ln(`    inset: (x: 8pt, y: 5pt),`);
      ln(`    align: (left, right, right, right, right),`);
      ln(`    table.hline(stroke: 1.2pt),`);
      ln(
        `    table.header([*Signal*], [*Slips*], [*Satellites*], [*Epochs*], [*Rate (/1k)*]),`,
      );
      ln(`    table.hline(stroke: 0.5pt),`);
      for (const s of csWithSlips) {
        ln(
          `    [${esc(s.label)}], [${String(s.totalSlips)}], [${String(s.satellites)}], [${String(s.totalEpochs)}], [${s.slipRate.toFixed(2)}],`,
        );
      }
      ln(`    table.hline(stroke: 1.2pt),`);
      ln(`  ),`);
      ln(`  kind: table,`);
      ln(
        `  caption: [Cycle slip detection summary — ${String(totalSlips)} total slips across ${csStats.length} signals (${csWithSlips.length} affected)],`,
      );
      ln(`) <tab-cycleslip>`);

      ln(``);
    } else {
      ln(`No cycle slips were detected across ${csStats.length} signals.`);
      ln(``);
    }

    if (chartFiles.includes('sliprate.svg')) {
      ln(`#figure(`);
      ln(`  image("/sliprate.svg", width: 100%),`);
      ln(`  caption: [Cycle slip rate per signal combination],`);
      ln(`) <fig-sliprate>`);
      ln(``);
    }
  }

  // ── 6. Data Completeness ───────────────────────────────────
  if (qaResult) {
    const compStats = qaResult.completeness.signalStats.filter(
      (s) => s.expected > 0,
    );
    const overallPresent = compStats.reduce((s, c) => s + c.present, 0);
    const overallExpected = compStats.reduce((s, c) => s + c.expected, 0);
    const overallPct =
      overallExpected > 0 ? (overallPresent / overallExpected) * 100 : 0;

    ln(`#pagebreak(weak: true)`);
    ln(`= Data Completeness`);
    ln(``);
    ln(`Overall observation completeness: *${overallPct.toFixed(1)}%*`);
    ln(``);

    // Per-constellation completeness charts
    const compSystems = chartFiles
      .filter((f) => f.startsWith('comp-'))
      .map((f) => f.replace('comp-', '').replace('.svg', ''));
    for (const sys of compSystems) {
      ln(`#figure(`);
      ln(`  image("/comp-${sys}.svg", width: 100%),`);
      ln(`  caption: [${esc(systemName(sys))} observation completeness],`);
      ln(`) <fig-comp-${sys}>`);
      ln(``);
    }

    if (compStats.length > 0) {
      const sorted = compStats.sort(
        (a, b) => systemCmp(a.system, b.system) || a.code.localeCompare(b.code),
      );
      // Group by constellation
      const sysGroups = new Map<string, typeof sorted>();
      for (const s of sorted) {
        let arr = sysGroups.get(s.system);
        if (!arr) {
          arr = [];
          sysGroups.set(s.system, arr);
        }
        arr.push(s);
      }
      for (const [sys, group] of sysGroups) {
        ln(`#figure(`);
        ln(`  table(`);
        ln(`    columns: (1fr, auto, auto, auto),`);
        ln(`    stroke: none,`);
        ln(`    inset: (x: 6pt, y: 3.5pt),`);
        ln(`    align: (left, right, right, right),`);
        ln(`    table.hline(stroke: 1.2pt),`);
        ln(
          `    table.header([*Signal*], [*Expected*], [*Present*], [*Completeness*]),`,
        );
        ln(`    table.hline(stroke: 0.5pt),`);
        for (const s of group) {
          ln(
            `    text(size: 8pt)[${esc(s.code)}], text(size: 8pt)[${String(s.expected)}], text(size: 8pt)[${String(s.present)}], text(size: 8pt)[${s.percent.toFixed(1)}%],`,
          );
        }
        ln(`    table.hline(stroke: 1.2pt),`);
        ln(`  ),`);
        ln(`  kind: table,`);
        ln(`  caption: [${esc(systemName(sys))} observation completeness],`);
        ln(`) <tab-comp-${sys}>`);

        ln(``);
      }
    }
  }

  // ── Annex: File listing ─────────────────────────────────────
  if (allFiles.length > 4) {
    ln(`#pagebreak(weak: true)`);
    ln(`#heading(numbering: none)[Annex — Input Files]`);
    ln(``);

    // Split into obs and nav groups
    const fileGroups: [string, string[]][] = [];
    if (obsFileNames.length > 0) fileGroups.push(['Observation', obsFileNames]);
    if (navFileNames.length > 0) fileGroups.push(['Navigation', navFileNames]);

    for (const [type, files] of fileGroups) {
      ln(`#text(10pt, weight: "bold")[${type} files (${files.length}):]`);
      ln(`#v(0.3em)`);
      ln(`#set text(8pt)`);

      // Multi-column table of filenames
      const cols = files.length > 30 ? 3 : files.length > 10 ? 2 : 1;
      ln(`#table(`);
      ln(`  columns: ${cols},`);
      ln(`  stroke: none,`);
      ln(`  inset: (x: 4pt, y: 2pt),`);
      for (const f of files) {
        ln(`  [#raw("${f}")],`);
      }
      ln(`)`);
      ln(`#v(0.8em)`);
    }
  }

  return lines.join('\n');
}

/* ================================================================== */
/*  Public API                                                          */
/* ================================================================== */

export async function generateReport(data: ReportData): Promise<Blob> {
  ensureInit();

  // Load branding logos
  let hasLogo = false;
  try {
    const logoResp = await fetch('/img/og-light.png');
    if (logoResp.ok) {
      await $typst.mapShadow(
        '/logo.png',
        new Uint8Array(await logoResp.arrayBuffer()),
      );
      hasLogo = true;
    }
  } catch {
    /* logo is optional */
  }

  // Generate print-themed SVG charts
  const encoder = new TextEncoder();
  const chartFiles: string[] = [];

  if (data.allPositions) {
    const svg = renderSkyPlotSvg(
      data.allPositions,
      data.observedPrns,
      5,
      PRINT_THEME,
    );
    await $typst.mapShadow('/skyplot.svg', encoder.encode(svg));
    chartFiles.push('skyplot.svg');
  }

  const cn0Svg = renderCn0TimelineSvg(data.grid, PRINT_THEME);
  if (cn0Svg) {
    await $typst.mapShadow('/cn0.svg', encoder.encode(cn0Svg));
    chartFiles.push('cn0.svg');
  }

  const satSvg = renderSatCountSvg(data.grid, PRINT_THEME);
  if (satSvg) {
    await $typst.mapShadow('/satcount.svg', encoder.encode(satSvg));
    chartFiles.push('satcount.svg');
  }

  // C/N0 distribution
  const cn0DistSvg = renderCn0DistributionSvg(data.grid, PRINT_THEME);
  if (cn0DistSvg) {
    await $typst.mapShadow('/cn0dist.svg', encoder.encode(cn0DistSvg));
    chartFiles.push('cn0dist.svg');
  }

  // Elevation vs C/N0
  if (data.allPositions) {
    const elevCn0Svg = renderElevCn0Svg(
      data.allPositions,
      data.grid,
      PRINT_THEME,
    );
    if (elevCn0Svg) {
      await $typst.mapShadow('/elevcn0.svg', encoder.encode(elevCn0Svg));
      chartFiles.push('elevcn0.svg');
    }
  }

  if (data.qaResult) {
    // Multipath charts
    if (data.allPositions) {
      const mpSvg = renderMultipathElevSvg(
        data.qaResult.multipath,
        data.allPositions,
        null,
        PRINT_THEME,
      );
      if (mpSvg) {
        await $typst.mapShadow('/multipath.svg', encoder.encode(mpSvg));
        chartFiles.push('multipath.svg');
      }
    }

    const mpBarSvg = renderMultipathRmsBarSvg(
      data.qaResult.multipath,
      PRINT_THEME,
    );
    if (mpBarSvg) {
      await $typst.mapShadow('/mp-rmsbar.svg', encoder.encode(mpBarSvg));
      chartFiles.push('mp-rmsbar.svg');
    }

    const mpSatSvg = renderMultipathPerSatSvg(
      data.qaResult.multipath,
      PRINT_THEME,
    );
    if (mpSatSvg) {
      await $typst.mapShadow('/mp-persat.svg', encoder.encode(mpSatSvg));
      chartFiles.push('mp-persat.svg');
    }

    // Cycle slip chart
    const slipSvg = renderCycleSlipRateSvg(
      data.qaResult.cycleSlips,
      PRINT_THEME,
    );
    if (slipSvg) {
      await $typst.mapShadow('/sliprate.svg', encoder.encode(slipSvg));
      chartFiles.push('sliprate.svg');
    }

    // Completeness charts (one per constellation)
    const compSvgs = renderCompletenessBarSvgs(
      data.qaResult.completeness,
      PRINT_THEME,
    );
    for (const c of compSvgs) {
      const name = `comp-${c.system}.svg`;
      await $typst.mapShadow(`/${name}`, encoder.encode(c.svg));
      chartFiles.push(name);
    }
  }

  // Build Typst source and compile
  const typstSource = buildTypstDocument(data, chartFiles, hasLogo);
  const pdfBytes = await $typst.pdf({ mainContent: typstSource });

  // Cleanup virtual filesystem
  for (const name of chartFiles) {
    await $typst.unmapShadow(`/${name}`);
  }
  if (hasLogo) await $typst.unmapShadow('/logo.png');

  if (!pdfBytes) throw new Error('PDF compilation failed');
  return new Blob([pdfBytes.buffer as ArrayBuffer], {
    type: 'application/pdf',
  });
}

export function downloadReport(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
